[project]
name = "rl-loans"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch>=2.6.0",
    "unsloth>=2025.3.17",
    "vllm>=0.8.1",
]
